repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: check-case-conflict

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        require_serial: true
        args: [--strict, --cache-dir=.mypy_cache]

-   repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
        args: ["--check"]

-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.1
    hooks:
    -   id: check-github-workflows
    -   id: check-dependabot

-   repo: https://github.com/pypa/pip-audit
    rev: v2.6.1
    hooks:
    -   id: pip-audit
